name: Build Artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - uses: actions/github-script@v7
        with:
          script: |
            const { default: buildArtifacts } = await import('${{ github.workspace }}/build-artifacts.js')
            await buildArtifacts()
